#!/bin/bash
if [ "$(id -u)" != "0" ]; then
        sudo $0
        exit 0
fi
#list=`lxc-ls -f | grep RUNNING | cut -d' ' -f1`
list=`lxc-ls -1 --running`

for f in $list
do
        echo $f
        lxc-attach -n "$f" -- ifdown eth0
        lxc-attach -n "$f" -- ifup eth0
done

